### PR TITLE
Add cargo-deny config and CI job

### PR DESCRIPTION
**Pull request by matthiasbeyer**
Taking [your word](https://github.com/Canop/termimad/issues/51#issuecomment-1786748628), lets have a `cargo-deny` CI job in this repository, so we do not run into issues like #51 again.

The job should fail as of latest master, as #51 is not resolved yet... so I'll rebase this as soon as the issue is fixed and then we should be good to go. :+1: :laughing:

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
Ah, you probably need to trigger CI for me as I am a new contributor to this repository.

**Comment by Canop** [comment]
> Ah, you probably need to trigger CI for me as I am a new contributor to this repository.

Hum... never had this situation. I don't find simpler solution than to add a commit on this branch. Is there one ?

**Comment by matthiasbeyer** [comment]
Ah, the button is called "Approve and run".

**Comment by Canop** [comment]
I don't find such button. Let's solve the real licence problem *then* merge this GH workflow.

**Pull request merged**
